window.WATCHLY_DEFAULT_MOVIES = [
  {
    "id": "oppenheimer",
    "title": "Oppenheimer",
    "category": "Biography, Drama",
    "genre": "Biography, Drama",
    "year": "2023",
    "duration": "120 min",
    "ageRating": "PG-13",
    "imdb": "4.5",
    "buyPrice": 10.99,
    "rentPrice": 2.59,
    "poster": "../img/movie/1/poster.webp",
    "heroBg": "https://m.media-amazon.com/images/M/MV5BNjI0ZmE0NjMtMzQ5ZS00N2RiLThkYzAtYjExOTc2MjU4ZGMzXkEyXkFqcGc@._V1_.jpg",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/7/7c/Oppenheimer_Movie_Logo_2023.png?utm_source=commons.wikimedia.org&utm_campaign=index&utm_content=original",
    "thumbnail": "https://i.ytimg.com/vi/gJ_tAMQWGsc/maxresdefault.jpg",
    "trailerImages": [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1sInBjX1c4StpDRX-4xrJkmu9cJOW4W-VGA&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1sInBjX1c4StpDRX-4xrJkmu9cJOW4W-VGA&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1sInBjX1c4StpDRX-4xrJkmu9cJOW4W-VGA&s"
    ],
    "description": "The life story of physicist J. Robert Oppenheimer and the development of the first nuclear weapons. A critically acclaimed epic film directed by Christopher Nolan.",
    "status": "published",
    "featured": false
  },
  {
    "id": "dune_part_two",
    "title": "Dune: Part Two",
    "category": "Sci-Fi, Adventure",
    "genre": "Sci-Fi, Adventure",
    "year": "2024",
    "duration": "120 min",
    "ageRating": "PG-13",
    "imdb": "4.7",
    "buyPrice": 7.99,
    "rentPrice": 1.2,
    "poster": "../img/movie/2/poster.webp",
    "heroBg": "https://www.azfamily.com/resizer/tsd1UhjphtW5RI6Tr0WzR4si-LU=/arc-photo-gray/arc3-prod/public/GPNM2O6SMVFRVJTAAWEWZ3QIB4.jpeg",
    "logo": "https://image.tmdb.org/t/p/original/eYvF1LhPKuoBxOAmWjFTAK7EPWl.png",
    "thumbnail": "https://i.ytimg.com/vi/jk4NU_lSjk8/maxresdefault.jpg",
    "trailerImages": [
      "https://i.ytimg.com/vi/_YUzQa_1RCE/maxresdefault.jpg",
      "https://i.ytimg.com/vi/U2Qp5pL3ovA/maxresdefault.jpg"
    ],
    "description": "The continuation of Paul Atreides' journey as he seeks revenge and unites the Fremen to gain control of the desert planet Arrakis.",
    "status": "published",
    "featured": false
  },
  {
    "id": "air",
    "title": "Air",
    "category": "Biography, Drama",
    "genre": "Biography, Drama",
    "year": "2023",
    "duration": "120 min",
    "ageRating": "PG-13",
    "imdb": "4.5",
    "buyPrice": 6.99,
    "rentPrice": 1.25,
    "poster": "../img/movie/3/poster.webp",
    "heroBg": "https://m.media-amazon.com/images/M/MV5BMmY3ZTIwOWQtMjg4Mi00NzgxLTlkM2EtYWFmNGYwNGI0NzYyXkEyXkFqcGdeQXNuZXNodQ@@._V1_.jpg",
    "logo": "https://m.media-amazon.com/images/S/pv-target-images/bf136b3a868e1ddb19c4864125d3d6b89b5670580a74fd74f58d234dbe9d470e.png",
    "thumbnail": "https://i.ytimg.com/vi/oUDOsAJrG-w/maxresdefault.jpg",
    "trailerImages": [
      "https://i.ytimg.com/vi/2tot_x9CjLI/maxresdefault.jpg",
      "https://i.ytimg.com/vi/Bwgr2EKfMSo/maxresdefault.jpg"
    ],
    "description": "The story behind the partnership between Nike and Michael Jordan that revolutionized basketball and culture.",
    "status": "published",
    "featured": false
  },
  {
    "id": "hit_man",
    "title": "Hit Man",
    "category": "Comedy, Action",
    "genre": "Comedy, Action",
    "year": "2023",
    "duration": "120 min",
    "ageRating": "PG-13",
    "imdb": "4.5",
    "buyPrice": 12.23,
    "rentPrice": 3.4,
    "poster": "../img/movie/4/poster.webp",
    "heroBg": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUtcXwxDoqExR8jyT6VeIbw0n81wkyFd8oKA&s",
    "logo": "https://1000logos.net/wp-content/uploads/2020/09/Hitman-Logo.png",
    "thumbnail": "https://i.ytimg.com/vi/XXL7FTl6ZCs/maxresdefault.jpg",
    "trailerImages": [
      "https://dnm.nflximg.net/api/v6/BvVbc2Wxr2w6QuoANoSpJKEIWjQ/AAAAQfJeBQeExOtVmzJjLwg0CMmrtTiQAwOJ1FApuLRDomKlKqRiMf11ND0tYp7hRc3UgSb8zZr5Ial4H5xSxy_YbHA5Jw4a-7vgjb7puCFiKhsWTMpTvzLy-nd-_0RpV-VU3_AMF4r8rY36TSFLesCJp9nE.jpg?r=d81",
      "https://i.ytimg.com/vi/NYojqkQFceY/maxresdefault.jpg"
    ],
    "description": "A college professor becomes a hit man of sorts in a darkly comedic turn of fate.",
    "status": "published",
    "featured": false
  },
  {
    "id": "back_to_black",
    "title": "Back to Black",
    "category": "Biography, Music",
    "genre": "Biography, Music",
    "year": "2024",
    "duration": "120 min",
    "ageRating": "PG-13",
    "imdb": "4.5",
    "buyPrice": 7.99,
    "rentPrice": 1.29,
    "poster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKBrOwdes-iEQ4vwwE_cPEQWp-7gAAca9xoA&s",
    "heroBg": "https://www.rollingstone.com/wp-content/uploads/2024/05/4213_D051_00230_R1714754556.jpg",
    "logo": "https://upload.wikimedia.org/wikipedia/fr/2/27/Back_to_Black_%28film%2C_2024%29.png?utm_source=fr.wikipedia.org&utm_campaign=index&utm_content=original",
    "thumbnail": "https://i.ytimg.com/vi/bWHz9zJth1s/maxresdefault.jpg",
    "trailerImages": [
      "https://i.ytimg.com/vi/VlW-jEscGgM/maxresdefault.jpg",
      "https://i.ytimg.com/vi/hPjCKW-NdWk/maxresdefault.jpg"
    ],
    "description": "A biographical film about the life and music of legendary singer Amy Winehouse.",
    "status": "published",
    "featured": false
  },
  {
    "id": "tron_legacy",
    "title": "Tron: Legacy",
    "category": "Sci-Fi, Action",
    "genre": "Sci-Fi, Action",
    "year": "2010",
    "duration": "120 min",
    "ageRating": "PG-13",
    "imdb": "4.5",
    "buyPrice": 15.99,
    "rentPrice": 4.99,
    "poster": "../img/movie/6/poster.webp",
    "heroBg": "https://i.ytimg.com/vi/P78pl1FUXfA/maxresdefault.jpg",
    "logo": "https://image.tmdb.org/t/p/original/1REQBg7DMBjb1de4CFnt7hBCXTf.png",
    "thumbnail": "https://i.ytimg.com/vi/u6r6tjbjO5U/maxresdefault.jpg",
    "trailerImages": [
      "https://i.ytimg.com/vi/AAKu9XvZybk/maxresdefault.jpg",
      "https://i.ytimg.com/vi/2S6qIn_4Wqw/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLBrKo2X6yma1vAMfd_xooVU73Xorg"
    ],
    "description": "A visually stunning continuation of the Tron universe where a young man enters the digital world to find his father.",
    "status": "published",
    "featured": false
  },
  {
    "id": "the_wolf_of_wall_street",
    "title": "The Wolf of Wall Street",
    "category": "Biography, Crime",
    "genre": "Biography, Crime",
    "year": "2013",
    "duration": "120 min",
    "ageRating": "PG-13",
    "imdb": "4.5",
    "buyPrice": 12.5,
    "rentPrice": 2.1,
    "poster": "../img/movie/7/poster.webp",
    "heroBg": "https://static01.nyt.com/images/2013/12/27/multimedia/movies-wolf-12272013/movies-wolf-12272013-superJumbo.jpg",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/The_Wolf_of_Wall_Street_logo.svg/1280px-The_Wolf_of_Wall_Street_logo.svg.png?utm_source=commons.wikimedia.org&utm_campaign=index&utm_content=thumbnail",
    "thumbnail": "https://i.ytimg.com/vi/idAVRvQeYAE/maxresdefault.jpg",
    "trailerImages": [
      "https://s1.dmcdn.net/v/Y5wMI1f_1DwfV9VEO/x480",
      "https://i.ytimg.com/vi/cz_J-DKNHMo/mqdefault.jpg"
    ],
    "description": "A wild true story based on the career of stockbroker Jordan Belfort.",
    "status": "published",
    "featured": false
  },
  {
    "id": "spider_man_across_the_universe",
    "title": "Spider-Man: Across the Spider-Verse",
    "category": "Animation, Action",
    "genre": "Animation, Action",
    "year": "2023",
    "duration": "120 min",
    "ageRating": "PG-13",
    "imdb": "4.5",
    "buyPrice": 6.99,
    "rentPrice": 1.28,
    "poster": "../img/movie/8/poster.webp",
    "heroBg": "https://variety.com/wp-content/uploads/2022/12/Screen-Shot-2022-12-13-at-12.03.18-PM.png",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/8/8b/Spider-Man_Across_the_Spider-Verse_logo.webp?utm_source=commons.wikimedia.org&utm_campaign=index&utm_content=original",
    "thumbnail": "https://i.ytimg.com/vi/WKLD9QEx9ks/maxresdefault.jpg",
    "trailerImages": [
      "https://i.ytimg.com/vi/cqGjhVJWtEg/maxresdefault.jpg",
      "https://i.ytimg.com/vi/shW9i6k8cB0/maxresdefault.jpg"
    ],
    "description": "Miles Morales' next big adventure through the multiverse.",
    "status": "published",
    "featured": false
  },
  {
    "id": "barbie",
    "title": "Barbie",
    "category": "Comedy, Adventure",
    "genre": "Comedy, Adventure",
    "year": "2023",
    "duration": "120 min",
    "ageRating": "PG-13",
    "imdb": "4.5",
    "buyPrice": 11.99,
    "rentPrice": 2.44,
    "poster": "../img/movie/9/poster.webp",
    "heroBg": "https://m.media-amazon.com/images/M/MV5BNGY0ZjA3MzAtYjIwOS00NTk5LThmMzEtNjI0MmU4MzQ1NmRiXkEyXkFqcGdeQWFybm8@._V1_.jpg",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/5/50/Barbie_%282023_movie_logo%29.png",
    "thumbnail": "https://i.ytimg.com/vi/pBk4NYhWNMM/maxresdefault.jpg",
    "trailerImages": [
      "https://i.ytimg.com/vi/qcGMKd8iego/maxresdefault.jpg",
      "https://i.ytimg.com/vi/R97vOlMD7q8/maxresdefault.jpg"
    ],
    "description": "A fun comedy-adventure set in the vibrant world of Barbie.",
    "status": "published",
    "featured": false
  },
  {
    "id": "guardians_of_galaxy_vol_3",
    "title": "Guardians of the Galaxy Vol. 3",
    "category": "Action, Sci-Fi",
    "genre": "Action, Sci-Fi",
    "year": "2023",
    "duration": "120 min",
    "ageRating": "PG-13",
    "imdb": "4.5",
    "buyPrice": 4.99,
    "rentPrice": 1.29,
    "poster": "../img/movie/10/poster.webp",
    "heroBg": "https://statcdn.fandango.com/MPX/image/NBCU_Fandango/559/3/guardiansV2.jpg",
    "logo": "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/a58a7719-0dcf-4e0b-b7bb-d2b725dbbb8e/df9wapx-2a7278ff-3e65-4524-a651-a0b349991285.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiIvZi9hNThhNzcxOS0wZGNmLTRlMGItYjdiYi1kMmI3MjVkYmJiOGUvZGY5d2FweC0yYTcyNzhmZi0zZTY1LTQ1MjQtYTY1MS1hMGIzNDk5OTEyODUucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.-CV4QtqHMZyPlB7hsd9ZdH-4SjMcphRh1mSaEA_-poM",
    "thumbnail": "https://i.ytimg.com/vi/u3V5KDHRQvk/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLABMW-6JRq8O__9TrQyzmWbOhyqpg",
    "trailerImages": [
      "https://i.ytimg.com/vi/JqcncLPi9zw/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLB9pwmoBU6t7AjZEj77Tca-y6we8A",
      "https://hips.hearstapps.com/hmg-prod/images/gotg-3-1669934046.jpg?crop=0.898989898989899xw:1xh;center"
    ],
    "description": "The final adventure of the Guardians as they protect the universe.",
    "status": "published",
    "featured": false
  },
  {
    "id": "fast_x",
    "title": "Fast X",
    "category": "Action, Adventure",
    "genre": "Action, Adventure",
    "year": "2023",
    "duration": "120 min",
    "ageRating": "PG-13",
    "imdb": "4.5",
    "buyPrice": 29.99,
    "rentPrice": 2.6,
    "poster": "../img/movie/11/poster.webp",
    "heroBg": "https://m.media-amazon.com/images/M/MV5BNjUyMDkzNzAtZjNjNC00YTQyLTg1MTQtNDJjM2QwZjFiYzA2XkEyXkFqcGdeQVRoaXJkUGFydHlJbmdlc3Rpb25Xb3JrZmxvdw@@._V1_QL75_UX500_CR0,0,500,281_.jpg",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/3/3d/Fast_X_logo.png?utm_source=commons.wikimedia.org&utm_campaign=index&utm_content=original",
    "thumbnail": "https://i.ytimg.com/vi/32RAq6JzY-w/maxresdefault.jpg",
    "trailerImages": [
      "https://i.ytimg.com/vi/yDk_Z3aIEbQ/maxresdefault.jpg",
      "https://i.ytimg.com/vi/eoOaKN4qCKw/maxresdefault.jpg"
    ],
    "description": "The tenth main installment in the Fast & Furious franchise.",
    "status": "published",
    "featured": false
  },
  {
    "id": "full_river_red",
    "title": "Full River Red",
    "category": "Action, Drama",
    "genre": "Action, Drama",
    "year": "2023",
    "duration": "120 min",
    "ageRating": "PG-13",
    "imdb": "4.5",
    "buyPrice": 9.99,
    "rentPrice": 0.99,
    "poster": "../img/movie/12/poster.webp",
    "heroBg": "https://variety.com/wp-content/uploads/2023/03/Full-River-Red.jpg?w=1000&h=563&crop=1",
    "logo": "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/346x192/v3/t/assets/p24243885_ttn_h95_aa.png",
    "thumbnail": "https://i.ytimg.com/vi/NL02h8VB3zo/maxresdefault.jpg",
    "trailerImages": [
      "https://i.ytimg.com/vi/1nrBhJE2w7E/maxresdefault.jpg",
      "https://i.ytimg.com/vi/1nrBhJE2w7E/maxresdefault.jpg"
    ],
    "description": "A martial arts epic and one of the top global box office hits of 2023.",
    "status": "published",
    "featured": false
  },
  {
    "id": "spider_man_into_the_spider_verse",
    "title": "Spider-Man: Into the Spider-Verse",
    "category": "Animation, Action",
    "genre": "Animation, Action",
    "year": "2018",
    "duration": "120 min",
    "ageRating": "PG-13",
    "imdb": "4.5",
    "buyPrice": 8.99,
    "rentPrice": 2.93,
    "poster": "../img/movie/13/poster.webp",
    "heroBg": "https://occ-0-8407-2218.1.nflxso.net/dnm/api/v6/6AYY37jfdO6hpXcMjf9Yu5cnmO0/AAAABUH5TDn3AiIbKdjxX1G2GpmNmah96L6FXuu1E1QHBx15CjgviZMM-5e7oisQcYukwV5HYpVe0qKGB7fyiXQXzsMygb-0ORwSKGmA.jpg?r=d3f",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/9/9d/Spider-Man_ITSV.png?utm_source=commons.wikimedia.org&utm_campaign=index&utm_content=original",
    "thumbnail": "https://i.ytimg.com/vi/rpMdiGYIIXY/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLArx36EmPZQz7psf-qRFX2py6FcvQ",
    "trailerImages": [
      "https://i.ytimg.com/vi/tg52up16eq0/maxresdefault.jpg",
      "https://i.ytimg.com/vi/g4Hbz2jLxvQ/maxresdefault.jpg"
    ],
    "description": "An award-winning animated Spider-Man film that reshaped superhero animation.",
    "status": "published",
    "featured": false
  },
  {
    "id": "the_super_mario_bros_movie",
    "title": "The Super Mario Bros. Movie",
    "category": "Animation, Adventure",
    "genre": "Animation, Adventure",
    "year": "2023",
    "duration": "120 min",
    "ageRating": "PG-13",
    "imdb": "4.5",
    "buyPrice": 7.99,
    "rentPrice": 4.78,
    "poster": "../img/movie/14/poster.webp",
    "heroBg": "https://www.hollywoodreporter.com/wp-content/uploads/2024/03/SuperMariosMCDSUMA_UV017.jpg?w=1296&h=730&crop=1",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/8/86/The_Super_Mario_Bros._Movie_logo.png?utm_source=commons.wikimedia.org&utm_campaign=index&utm_content=original",
    "thumbnail": "https://i.ytimg.com/vi/TnGl01FkMMo/maxresdefault.jpg",
    "trailerImages": [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAmjFcb6JlcqStKkkzPwZkf9vi3t5muikLbw&s",
      "https://i.ytimg.com/vi/RjNcTBXTk4I/maxresdefault.jpg"
    ],
    "description": "A beloved animated adventure based on the classic Nintendo game.",
    "status": "published",
    "featured": false
  },
  {
    "id": "killers_of_the_flower_moon",
    "title": "Killers of the Flower Moon",
    "category": "Crime, Drama",
    "genre": "Crime, Drama",
    "year": "2023",
    "duration": "120 min",
    "ageRating": "PG-13",
    "imdb": "4.5",
    "buyPrice": 10.87,
    "rentPrice": 2.56,
    "poster": "../img/movie/15/poster.webp",
    "heroBg": "https://angelusnews.com/wp-content/uploads/2023/10/Killers_Of_The_Flower_Moon_Photo_0108-scaled.jpg",
    "logo": "https://image.tmdb.org/t/p/original/1byCcdBqQi9CI50xQTA4cjmVCxf.png",
    "thumbnail": "https://i.ytimg.com/vi/N36XgbzQZYM/maxresdefault.jpg",
    "trailerImages": [
      "https://i.ytimg.com/vi/EG0si5bSd6I/maxresdefault.jpg",
      "https://i.ytimg.com/vi/mIH1FHykKRY/maxresdefault.jpg"
    ],
    "description": "Based on true events, this film follows the serial murders of Osage Nation members in 1920s Oklahoma after oil is discovered on their land.",
    "status": "published",
    "featured": false
  }
];
